### ISSUE TITLE
Hardware Requirements for Running This Code

### ISSUE THREAD

**Issue by shenmuxing** [likenneth/q_probe#1]
Thanks for sharing the code for your paper. I'd like to try replicating your experiments. Could you please provide some details on the hardware requirements to run the code effectively? Specifically, would a GPU with 24GB of memory be sufficient?

**Comment by likenneth** [comment]
Hello, it should be. The experiment takes two steps: first to extract feature vectors to local; second to train various probe and get the results. 
Step 1 might be doable but can be time-consuming if you don't parallelize. However, you can download from my google drive (link in repo). A 24G GPU is more than enough for Step 2.

**Comment by shenmuxing** [comment]
Thanks for your reply! I ran the code in `code_exp` successfully.
